// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"
)

type Querier interface {
	CreateEEGSession(ctx context.Context, arg CreateEEGSessionParams) error
	GetEEGDataByEEGSessionId(ctx context.Context, arg GetEEGDataByEEGSessionIdParams) ([]EegDatum, error)
	GetEEGSessionByID(ctx context.Context, id uint64) (EegSession, error)
	GetEEGSessionByUID(ctx context.Context, uid uint64) ([]EegSession, error)
	GetLatestEEGSession(ctx context.Context) (EegSession, error)
	GetLatestUser(ctx context.Context) (User, error)
	GetMessage(ctx context.Context, arg GetMessageParams) ([]Message, error)
	GetSubscribePair(ctx context.Context, arg GetSubscribePairParams) (Subscriber, error)
	GetUnfinishedEEGSession(ctx context.Context) ([]EegSession, error)
	GetUnfinishedEEGSessionByUID(ctx context.Context, uid uint64) ([]EegSession, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByMobile(ctx context.Context, mobile string) (User, error)
	GetUserByUid(ctx context.Context, id uint64) (User, error)
	InsertEEGData(ctx context.Context, arg InsertEEGDataParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) error
	InsertSubscribePair(ctx context.Context, arg InsertSubscribePairParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	ListSubscribePairBySuid(ctx context.Context, arg ListSubscribePairBySuidParams) ([]Subscriber, error)
	ListSubscribePairByUid(ctx context.Context, arg ListSubscribePairByUidParams) ([]Subscriber, error)
	ListUserReceivedMessages(ctx context.Context, arg ListUserReceivedMessagesParams) ([]Message, error)
	ListUserSentMessages(ctx context.Context, arg ListUserSentMessagesParams) ([]Message, error)
	UpdateEEGSession(ctx context.Context, arg UpdateEEGSessionParams) error
	UpdateSubscribePair(ctx context.Context, arg UpdateSubscribePairParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
